name: Test (Windows)

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events for main and release branches
  pull_request:
    branches: [main, release_*, release-*]

  push:
    branches: [main, release_*, release-*]
    paths-ignore:
      - "document/**"
      - "*.md"
      - "*.mdx"

  merge_group:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # ======== ut ========
  ut-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [22.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git config
        shell: bash
        run: |
          git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 10

      - name: Install Pnpm
        run: |
          npm install -g corepack@latest --force
          corepack enable

      - name: Check skip CI
        shell: bash
        run: echo "RESULT=$(node ./scripts/skipCI.js)" >> "$GITHUB_OUTPUT"
        id: skip-ci

      - name: Log skip CI result
        run: echo "${{steps.skip-ci.outputs.RESULT}}"

      - name: Setup Node.js ${{ matrix.node-version }}
        if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
        run: pnpm install

      - name: Unit Test
        if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
        run: pnpm run test

  # # ======== e2e ========
  # e2e-windows:
  #   runs-on: windows-latest
  #   strategy:
  #     matrix:
  #       node-version: [18.x]

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     - name: Git config
  #       shell: bash
  #       run: |
  #         git config --system core.longpaths true

  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 10

  #     - name: Install Pnpm
  #       run: corepack enable

  #     - name: Check skip CI
  #       shell: bash
  #       run: echo "RESULT=$(node ./scripts/skipCI.js)" >> "$GITHUB_OUTPUT"
  #       id: skip-ci

  #     - name: Log skip CI result
  #       run: echo "${{steps.skip-ci.outputs.RESULT}}"

  #     - name: Setup Node.js ${{ matrix.node-version }}
  #       if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'pnpm'

  #     - name: Install Dependencies
  #       if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
  #       run: pnpm install && cd ./e2e && npx playwright install

  #     - name: E2E Test
  #       if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
  #       run: pnpm run e2e
